# Generated by Django 4.2.5 on 2024-05-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('siglas', models.CharField(max_length=32)),
                ('pais', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProfesor', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('nombramientoActual', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('extra', models.TextField(blank=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconocimientos', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicosR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productosAcademicosR', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionOrganismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('nivel', models.CharField(max_length=128)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacionOrganismos', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='LogrosProfesionalesNoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('relevancia', models.CharField(max_length=128)),
                ('autores', models.CharField(max_length=128)),
                ('sede', models.CharField(max_length=128)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logrosProfesionalesNoA', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadPuesto', models.TextField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestionAcademica', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Especialización', 'Especialización'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], max_length=64)),
                ('nombre', models.CharField(max_length=256)),
                ('añoObtencion', models.DateField()),
                ('cedulaProfesional', models.CharField(max_length=256)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formacionAcademica', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='ExpProfesionalNoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadPuesto', models.TextField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expProfesionalNoA', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='ExpDiseñoIngenieril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('nivel', models.CharField(max_length=128)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expDiseñoIngenieril', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCapacitacion', models.CharField(max_length=256)),
                ('añoObtencion', models.DateField()),
                ('horas', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacionDocente', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportacion', to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoActualizacion', models.CharField(max_length=256)),
                ('añoObtencion', models.DateField()),
                ('horas', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.institucion')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actualizacionDisciplinar', to='Maestro.maestro')),
            ],
        ),
    ]
