# Generated by Django 4.2.5 on 2024-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacionacademica',
            name='evidencia',
            field=models.ImageField(null=True, upload_to='FormacionesAcademica/'),
        ),
    ]
